[package]
edition = "2021"
name = "zome_0"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "zome_0"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
derive_more = "0"

zome_0_integrity = { path = "../../integrity_zomes/zome_0_integrity" }